name: personalweb

services:
    backend:
        build: backend
        env_file:
            - backend/.env
        restart: on-failure
        expose:
            - 3000
    frontend:
        build: frontend
        ports:
            - "3000:5173"
