name: personalweb

services:
    proxy:
        build: .
        ports:
            - "80:80"
        networks:
            - frontnet
    frontend:
        build: frontend
        ports:
            - "5173:5173"
        networks:
            - frontnet
            - backnet
    backend:
        build: backend
        env_file:
            - backend/.env
        restart: on-failure
        ports:
            - "3000:3000"
        networks:
            - backnet
networks:
    frontnet:
    backnet:
